services:
  # Servicio de la API FastAPI
  api:
    image: ${API_IMAGE:-pdf-extractortext-api}:${API_VERSION:-latest}
    container_name: pdf-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - docker/.env
    networks:
      - pdf-extractortext_pdf-network

networks:
  pdf-extractortext_pdf-network:
    driver: bridge
    external: true